# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2020-06-16 06:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=32, verbose_name='目标城市')),
                ('min_distance', models.IntegerField(default=1, verbose_name='最小距离')),
                ('max_distance', models.IntegerField(default=10, verbose_name='最大距离')),
                ('min_dating_age', models.IntegerField(default=18, verbose_name='最小交友年龄')),
                ('max_dating_age', models.IntegerField(default=45, verbose_name='最大交友年龄')),
                ('dating_sex', models.CharField(choices=[('男', '男'), ('女', '女')], max_length=8, verbose_name='匹配性别')),
                ('vibration', models.BooleanField(default=True, verbose_name='开启震动')),
                ('only_matche', models.BooleanField(default=True, verbose_name='禁止其他人看相册')),
                ('auto_play', models.BooleanField(default=True, verbose_name='是否自动播放视频')),
            ],
            options={
                'verbose_name': '用户配置信息',
                'verbose_name_plural': '用户配置信息',
                'db_table': 'profile',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=32, unique=True, verbose_name='昵称')),
                ('phonenum', models.CharField(max_length=16, unique=True, verbose_name='手机号')),
                ('sex', models.CharField(choices=[('男', '男'), ('男', '女')], max_length=8, verbose_name='性别')),
                ('birth_year', models.IntegerField(verbose_name='出生年份')),
                ('birth_month', models.IntegerField(verbose_name='出生月份')),
                ('birth_day', models.IntegerField(verbose_name='出生日期')),
                ('avatar', models.CharField(max_length=256, verbose_name='头像url')),
                ('location', models.CharField(max_length=32, verbose_name='常居地址')),
            ],
            options={
                'verbose_name': '用户信息',
                'verbose_name_plural': '用户信息',
                'db_table': 'user',
            },
        ),
    ]
